doc/src/records/gain.md, doc/src/records/importfile.md, src/ANCREC.H, src/BRFW.CPP, src/BRFW.H, src/CGCOMP.CPP, src/CNAUSZ.CPP, src/CNCULT.H, src/CNCULT4.CPP, src/CNDTYPES.DEF, src/CNGLOB.H, src/CNGUTS.CPP, src/CNRECS.DEF, src/CSE.cpp, src/CSEFace.H, src/CUL.H, src/CUPARSE.CPP, src/CUTOK.CPP, src/DMPAK.H, src/IMPF.CPP, src/IMPF.H, src/RMKERR.CPP, src/STRPAK.CPP
- Improved warnings and errors re IMPORTFILE non-unique column names.
- Comment cleanup (e.g. "cne" changed to "cse")
=> Import fixes

src/DHWCalc.cpp, src/STRPAK.CPP
Use DTZ to reduce DHWSYS wsWriteDrawCSV file size
=> Fixes in WStrDTZ.

doc/README.md, doc/lib/coverage_check.rb, doc/lib/table.rb, doc/lib/template.rb, doc/rakefile.rb, doc/test/coverage_check_test.rb, doc/test/table_test.rb
Addresses issue 81 and issue 65 (duplicate).
I've attached the coverage report output before and after the fix which demonstrates the fix (see the diff image below; raw files are available as well). I've also updated the docs unit tests (from the docs directory, type `rake test` if you'd like to run them yourself) to verify this fixes the issue.
README has also been updated to clarify some installation requirements and have also run unit tests for Ruby 2.4 - 2.7.
[after-fix.txt](https://github.com/cse-sim/cse/files/4140957/after-fix.txt)
[prior-to-fix.txt](https://github.com/cse-sim/cse/files/4140958/prior-to-fix.txt)
=> Fix issue 81+issue 65

.github/workflows/build-and-test.yml
This change enforces upload artifact version 2.2.4.
=> Enforce upload artifact version 2.2.4.

src/CNRECS.DEF, src/RCDEF.CPP
The generating files were creating extra qualifications inside the member functions of some classes. MSVC was allowing C++ to write classes like so, however, GCC does not allow it.
=> Remove extra qualification

src/XIOPAK.CPP, test/CMakeLists.txt
Fixes the bug where adding an extension prevents the CSE from finding the file. Now, it reads either "filename" or "filename.cse". 
I tested the code by being in `cse/msvc/` and running the following cases:
- CSE.exe ../test/1ZAttic.cse // Pass
- CSE.exe ../test/1ZAttic      // Pass
- CSE.exe 1ZAttic                // Fails - P0003: Cannot open file 'C:\USERS\GALAN\DOCUMENTS\BIG LADDER SOFTWARE\CSE\MSVC\1ZATTIC'
- CSE.exe falsefolder/1ZAttic // Fails - Error: "falsefolder/1ZAttic": Invalid path
- CSE.exe falsefolder/1ZAttic.cse // Fails - Error: "falsefolder/1ZAttic.cse": Invalid path
=> Fixes extra extension added to filename.

src/CNGUTS.CPP, src/CNRECS.DEF
Consolidation of _DEBUG checking that MTRs are accumulated correctly.
(MTR accumulation is tricky due to PV and BT.)
=> Improve validation in MTR accum

.github/workflows/build-and-test.yml, .github/workflows/release.yml
Exclude the git folder from the documentation artifact.
=> Exclude git from documentation artifact.

doc/src/records/airhandler.md, doc/src/records/terminal.md, src/CNAH1.CPP, src/CNAUSZ.CPP, src/CNCULT.CPP, src/CNCULT5.CPP, src/CNLOADS.CPP, src/CNRECS.DEF, src/CNZTU.CPP
All sizing factors are now a multiplier instead of the fraction oversized, e.g., 1.2 instead of 0.2.
=> Make TERMINAL and AIRHANDLER sizing factors consistent with RSYS

doc/src/records/airhandler.md, src/CMakeLists.txt, src/CNAH1.CPP, src/CNCOIL.CPP, src/CNCULT.CPP, src/CNCULT5.CPP, src/CNLOADS.CPP, src/CNRECS.DEF, src/HVAC.CPP, src/HVAC.H, src/PSYCHRO.CPP, src/PSYCHRO.H
=> Make AIRHANDLER autosized heat pump capacities consistent

src/CGRESULT.CPP, src/CSE.cpp
When no simulation is performed, CSE suppress all reports/exports except TUSIZE and AHSIZE.  However, UDT export is needed for CBECC autosizing process.
Fix = include UDT in the autosize-only report/export set.  Caveat-user ... but the idea is the user knows what s/he is doing if they're UDTing.
=> Include UDT in autosize-only report set

doc/src/records/airhandler.md, src/CNCOIL.CPP, src/CNCULT5.CPP
Use ahccSHRRat (or defaulted value) to default ahccCapSRat when ahccCapTRat isn't AUTOSIZED.
=> Remove ahccCapSRat requirement when not AUTOSIZING

src/CNAH1.CPP, src/CNAH2.CPP, src/CNCOIL.CPP, src/CNCULT.CPP, src/CNCULT2.CPP, src/CNCULT5.CPP, src/CNDEFNS.H, src/CNFAN.CPP, src/CNGUTS.CPP, src/CNZTU.CPP, src/CUEVAL.CPP, src/CUL.CPP, src/CUL.H, src/CUPARSE.CPP, src/CUPROBE.CPP, src/CUTOK.H, src/EXMAN.CPP, src/RCDEF.CPP
Removes AUTOSIZE preprocessor as if true. This fixes issue #224.
The test that was performed to make sure no changes were added, was comparing the I-files from the preprocessor in the master branch to I-files of the final output using the software beyond compare.
=> Remove AUTOSIZE preprocessor as if defined

src/CNCOIL.CPP, src/CNDTYPES.DEF, src/MSGTBL.CPP
Replaces the warnings about actual airflow being substantially different from rated airflow with warnings when the actual airflow is outside a reasonable range of CFM/ton.
This also fixes an issue where CSE input did not recognize choice inputs with spaces.
=> Modify AIRHANDLER coil airflow warnings

cmake/preprocess.cmake, src/CMakeLists.txt
Updates CMakelist and other CMake files, to be able to compile CSE in all three platforms. This PR is part of the multiplatform series of PR to make CSE a multiplatform software. This should create no changes in the windows CSE build.
=> Modify cmake to allow for other platform to compile.

src/CNAH1.CPP, src/CNCOIL.CPP, src/CNCULT5.CPP, src/CNRECS.DEF
- Make cooling coil airflow checks consistent between autosizing and user input sizing
- Only warn about renormalizing curves if the difference is more than 2%
=> Soften coil warnings

src/TDPAK.H
Removes extra qualification on calendar constructor in TDPAK.H.
=> Remove extra qualification in calendar constructor.

doc/src/records/doas.md, src/CGCOMP.CPP, src/CNCOIL.CPP, test/Multifamily-DOAS.cse
Also relaxes the tolerance for air handler CFM/ton checks. i.e., allows for floating point precision differences so that 279.9 isn't flagged for being below 280.
=> Allow DOAS setpoints to be set for bypass control when there are no tempering coils

cmake/initialize-submodules.cmake
Adds git hook bash files to ensure submodules are updated properly. This will only happen for git hooks that are not already defined. The user can also disable this feature through a CMake option (`CREATE_GIT_HOOKS`).
=> Add git-hooks to manage submodules by default

src/geometry.cpp, src/geometry.h
Removes `USE_MFC` definitions and other comments related to MFC.
=> Remove USE_MFC and other MFC comments.

CMakeLists.txt, src/shading.cpp, vendor/CMakeLists.txt
Updates CSE to use the latest penumbra release. 
- Remove awning and uninstall from build target
- Rename calculatePSSF to calculate PSSA
- Change the cast typedef to match input typdef for callback function.
- Upgrades penumbra to a working branch [modernize-compiler-flags](https://github.com/bigladder/penumbra/tree/modernize-compiler-flags) once said branch is merged to penumbra/master another checkout shall be done to penumbra/master.
Uses shading.cpp to test for regression.
=> Update penumbra submodule to the latest 

src/cnglob.h
Restore missing #define DEBUG and #define DEBUG2 in cnglob.h
=> Add missing debug #defines

.gitignore, CMakeLists.txt, cmake/BuildFlags.cmake, src/cnglob.h, src/dmpak.cpp, src/envpak.cpp, src/rmkerr.cpp, src/strpak.cpp, src/strpak.h
=> Make native preprocessor definitions for build configurations

cmake/BuildFlags.cmake, src/cndefns.h, src/cnglob.h, src/dmpak.cpp, src/envpak.cpp, src/rmkerr.cpp, src/strpak.cpp, src/strpak.h
- In cnglob.h, #include cndefns.h as the first step as opposed to later.
- Move all configuration CSE_XXX macro #defines to cndefns.h to make them available to rcdef-processed files.
- Change CSE_XXX scheme to use integer values as opposed to simple #defines.
- Verified DEBUG and RELEASE builds, ran all tests.
-
=> Relocate cndefns.h; change CSE_XXX defines to constants

src/messages.cpp
`sys_nerr` and `sys_errlist` have been deprecated and thus they are being removed from the code base.
This solution builds in MSVC, GCC, and Clang.
=> Remove sys_nerr and sys_errlist.

src/dhwcalc.cpp
Fix bug re LDEF calculation for heat pump water heaters (T24DHW model).
=> DHW whEF=1 ideal efficiency bug fix

doc/src/output-reports.md, doc/src/records/afmeter.md
Add documentation for columns displayed in Air Flow Meter Report (REPORT rpType=AFMETER)
=> Add documentation for REPORT rpType=AFMETER

src/cnglob.h, src/cutok.cpp, src/messages.cpp
- Fixes overflow of the `char* where`, by secure sprintf (snprintf). 
- Replace hard-coded length with known definitions
- Add a message for no file or directory found.
This was tested by giving a long name input file path.
=> Fix path character limit

doc/src/records/rsys.md, src/cnloads.cpp
Minor corrections to dual-fuel heat pump model
- Change default rsAFUEAuxH to 0.9 when rsTypeAuxH=FURNACE
- Correct and expand dual-fuel documentation
- Fix typo in error message
=> DFHP documentation corrections; default rsAFUEAuxH=0.9 for fuel auxH

src/cgresult.cpp, src/cncult4.cpp, src/cse.cpp, src/pp.cpp, src/strpak.cpp, src/strpak.h, test/unit/strpak.unit.cpp
- Replace faulty strReplace() with safe version that checks destination buffer size.
- Updated strReplace() unit tests.
- Several strpak.cpp and calling code cleanups.
- Use strReplace() to add the prefix option to command line for display in output
=> Fix report file comment line

src/cutok.cpp
Enlarged cuErv() temporary buffer 'where' that was overrun for long messages.
Also did some local cleanup, e.g. moved declarations to point of use.
No test results impacts.
=> Fix long message buffer overrun

doc/src/operation.md, doc/src/records/izxfer.md, src/ancrec.cpp, src/ancrec.h, src/cgcomp.cpp, src/cncult3.cpp, src/cnglob.h, src/cnguts.cpp, src/cpgbuild.cpp, src/cse.cpp, src/cueval.cpp, src/cul.cpp, src/cuparse.cpp, src/cvpak.cpp, src/envpak.cpp, src/exman.cpp, src/impf.cpp, src/msgtbl.cpp, src/mspak.cpp, src/pp.cpp, src/rmkerr.cpp, src/shading.cpp, src/sytb.cpp, src/vrpak.cpp, src/yacam.cpp, src/yacam.h
Dropped user prompt after error messages that allowed entering 'A' for abort, any other key to continue.
Now most messages display and execution continues.  Repeated messages will stop execution due to errorCount limit.
In addition, many comments on error reporting calls have been modified to remove the "wait for keypress" (or similar) in the wording.
Updated description of command line options in documentation.  Added description for missing options.
Reviewed documentation to see if keypress behavior is described.  Apparently not.  No changes made.
No test results changes.
=> Eliminated wait-for-keypress after error msg display

src/cnglob.h, src/cvpak.h, test/unit/CMakeLists.txt, test/unit/cvpak.unit.cpp
- Added new unit test for cvpak.
- Added a few test for cvin2s()
- More test needed for additional data types and other functions.
=> Add basic cvpak cvin2s() tests

doc/src/records/door.md, doc/src/records/ductseg.md, doc/src/records/surface.md, doc/src/records/window.md, src/CNRECS.DEF
**Enforce non-negative surface convection coefficients**
- The current documentation indicates a legal range of $x > 0$ for DUCTSEG member data `dsExH`, but this was not enforced in the cse code. It was determined that a legal range of $x \ge 0$ is physically reasonable, Division by zero is prevented by the existing code. The CNRECS.DEF entries for dsExH and related variables were changed to `FLOAT_GEZ`. A change to the cse manual was made to indicate the valid range for `dsExH`.
- These changes fix issue #407.
- Simulations were run with zero and negative values of `dsExH`. Each instance of a negative `dsExH` entry presents an appropriate message, such as
E0095: Bad dsExH: -1: V0023: value must be 0 or greater
and the run is blocked.
=> Enforce non-negative surface convection coefficient `dsExH`

src/cul.h
Fix logic error in CULT::cu_GetArraySize().  cu_GetArraySize() is sometimes deliberately called on a non-array member, generating a spurious assert (in debug builds).
Recoded to return 0 for a non-array.
No test result changes.
=> Fix incorrect assert() in CULT::cu_GetArraySize()

src/cncult3.cpp, test/1ZAttic.cse, test/2ZAttic.cse, test/CRTerminalAH.cse, test/Zonetest4W.cse, test/actest1bL.cse, test/dhw_zone.cse, test/ref/1ZATTIC.REP, test/ref/2ZATTIC.REP, test/ref/CRTERMINALAH.REP, test/ref/DHW_ZONE.REP
Motivation
For the boundary condition of `sfExCnd = SPECIFIEDT`, this bug caused `hcNat` to be incorrectly set equal to the value of `sfExH`. This caused the user input of `sfExHcMult` to be different than the output of probe `sbcO.hxa`.
Changes
- Use `sb_HCAmbient()` to calculate `hcNat` instead of setting `hcNat` equal to `sfExH`.
- Change the calculation of `sb_hxa` from `sb_hcMult * sb_hcNat` to `sb_hcMult * (sb_hcNat + sb_hcFrc)`.
- Update CSE files in test directory to reflect changes made to `hcNat` calculation. A more thorough explanation is below in the Tests Performed section.
- Update REP files in `test\ref` directory.
Result
`hcNat` is correctly calculated as intended, which is a value of `1`, and the input `sfExHcMult` is equal to the output of probe `sbcO.hxa`.
Tests …
=> Fix exterior convection heat transfer coefficient for specified temperature boundary condition

.github/actions/download-cse-artifact/action.yml, .github/workflows/build-and-test.yml, .github/workflows/release.yml
Updates the versions of GitHub actions to remove warnings about deprecated versions of Node.
Note: This also makes artifacts immediately available for download once they are uploaded.
=> Update GitHub action versions

doc/src/records/dhwheater-doc.md
Added descriptions of generic models to user manual, as provided by B. Larson.
=> Add generic entries.

doc/package.json
Updates html-minifier to a more secure version (4.0.0).
=> Update docs dependency to avoid security risk

doc/src/records/izxfer.md
Replaces documentation of general interzone airflow categories with conditioned/unconditioned distinctions.
=> Update izAFCat documentation
