- src/ANCREC.CPP
- src/ANCREC.H
- src/CNCULT.CPP
- src/CNDEFNS.H
- src/CNRECS.DEF
- src/PVCalc.cpp
- src/SHADING.CPP
- test/ref/ACTEST1BL.REP
- vendor/ASHRAE/geometry.h
> SHADEX and PVARRAY vertex input.

- src/CMakeLists.txt
src\cmakelists.txt bug fix re *.def file name modification for rcdef preprocessing
> Fix rcdef input file preprocessing file name preparation.

- cmake/preprocess.cmake
- src/CMakeLists.txt
@chipbarnaby this doesn't exactly solve our problem, but it helps debug the problems in the future. I suspect there was something strange happening with CMake where it wasn't checking to make sure dependencies existed and would skip the command entirely if there weren't any existing dependencies.
> Make special script for debugging C Preprocessor issues.

- doc/src/records/dhwheater.md
- src/CNCULT.CPP
- src/CNRECS.DEF
- src/DHWCalc.cpp
Allow user specification of end use for accounting of virtual DHW resistance heater energy.  Default end use is dhwBU, so change is backward compatible.  With additional into, "real" backup (e.g. HPWH resistance heat) can be distinguished from energy used to maintain wsTUse.
Also some incomplete / harmless groundwork for volume vs duration draw modeling.
> Added water heater wsTUse re-heat (whxBU) end use assignment

- src/CNGUTS.CPP
- src/CNLOADS.CPP
- src/CNRECS.DEF
- src/CNZTU.CPP
Tracks magnitude of failure to hold heating and cooling set points.
> Add ZNRES unMetHDH and unMetCDH = unmet degree hours

- .github/workflows/release.yml
Not much to review here. Just fixing the "add to path" command on the CI now that we've moved the default shell to bash.
I've tested by making a [draft release](https://github.com/cse-sim/cse/releases/tag/v0.900.1) that we can make official or delete.
> Fix CI release deployment of documentation

- src/XIOPAK.CPP
- src/XIOPAK.H
Fixes a conversion warning, having a possible loss of data from USI to size_t.
> Fix possible loss of data warning.

- cmake/CSEVersion.cmake
Builds that are at a tagged revision should version CSE with the tag only; no metadata. This aspect got inadvertently removed during the semantic-versioning fix.
> Add back the check for versioning directly on a tag (removed by mistake)

- doc/src/records/dhwheater-doc.md
- src/CNRECS.DEF
- src/cncult.cpp
- src/dhwcalc.cpp
- test/DHWDU.cse
- test/DHW_C.cse
- test/ref/DHW_C.REP
Added DHWHEATER whFEff = primary efficiency factor.  Supports CBECC-Res use cases for approximating air to water heat pumps.
Updated associated documentation and test files.
> Add DHWHEATER whFEff efficiency modifier

- src/CNRECS.DEF
- src/cgresult.cpp
- src/cndefns.h
- src/cnguts.cpp
- src/cvpak.cpp
- test/ref/submeter.rep
- test/submeter.cse
Modifications to built-in report generation machinery in cgresult.cpp provide support for double-precision data.  The report scheme is table-driven with one row per report column.  A new flag allows indicating that the data being accessed is double as opposed to float.
Improved generalized data access functions added to support that change.
Testing was performed by changing MTR end use data via conditional code controlled by METER_DBL (cndefns.h).  Reported results were virtually identical to those with float data even for complex MTR schemes with submeters.  METER_DBL left #undef'd but the conditional code retained for future experiments.
Test file submeter.cse updated to better test submeters with multipliers.
> Support double-precision data in reports; experiment with double-precision MTR data

- doc/src/records/report.md
- src/cncult4.cpp
- test/ref/commands.rep
Fix bug associated with REPORT rpCpl.
Issue: When rpCpl was recalculated during setup due report-too-wide, the recalculated value was retained into subsequent runs (that is, the input record was modified).  Bad case:
1. Input or default rpCpl=-1 ("as wide as needed') in a REPORT
2. Run
3. Modify the REPORT to make it wider (e.g., add a REPORTCOL)
4. Run
5. Get superfluous warning about insufficient width.
Local value introduced to allow width recalc to occur w/o modifying input value.
Also replaced test case result commands.rep (test case commands.cse was where the problem was discovered).
Also clarified documentation for REPORT rpCpl
> Fix rpCpl multi-run bug

- src/CNRECS.DEF
- src/cul.cpp
- src/cutok.cpp
- src/pp.cpp
Replaces 16-bit line number variables with 32-bit ints in a few places.  This fixes incorrect line number display in error messages generated by projects having very large input files (> 65,000-ish lines).
The known case exhibiting this problem retested OK.
All code reviewed for similar situations.  Several other 16-bit values are changed to int.
No results changes.  All tests pass.  No documentation changes.
> Fix line number tracking and reporting (changed SI/USI values to int)

- doc/src/records/battery.md
Added explanation and example re use of BATTERY btChgReq.
No code changes; no results changes.
> Explanation and example for BATTERY btChgReq

- src/CNRECS.DEF
- src/ancrec.h
- src/cnausz.cpp
- src/cncult2.cpp
- src/cncult3.cpp
- src/cnloads.cpp
64-bit development found an instance of IsSet( record-member) where IsSet( record-member-field-number) was intended.
This PR includes several changes to field status access and testing functions to check that the fn (field number) is an integer.  With this, the original offending error was detected along with several more.  All have been fixed.
A more robust fix would be to define a type for field number.  An issue has been added.
No results changes.  No regression test changes.  No documentation changes.
> Improved field number type checking; correct bad usage detected

- src/cueval.cpp
- src/cuparse.cpp
Minor cleanup.  cueval.cpp and cuprobe.cpp had code within #if defined( PROBE) and #if define( IMPORT).
These features are permanent and the need to link this code in other contexts does not exist.   Conditionals have been coded out.
No results or documentation changes.
> Code out conditionalability for IMPORT and PROBE

- doc/src/records/importfile.md
IMPORTFILE documentation changes
- Included newly added SUBHOUR choice for imFreq
- Added note regarding file order.  Forward references to IMPORTFILEs can cause variability errors because file imFreq is not known until IMPORTFILE is processed.
No code changes.  No results changes.
> Update IMPORTFILE documentation

- doc/src/records/top-members.md
- src/CNRECS.DEF
- src/cgcomp.cpp
- src/cnausz.cpp
- src/cncult.cpp
- src/cncult2.cpp
- src/cnguts.cpp
- src/cnguts.h
- src/cnloads.cpp
- test/ASHPTest2.cse
- test/ref/ASHPPKGROOM.REP
- test/ref/ASHPTEST2.REP
Motivation: improve user control of AirNet errors and warnings.
Added two inputs: Top.ANPressWarn (default = 5 lb/ft2) and Top.ANPressErr (default = 30 lb/ft2) which set the pressure thresholds for warning and errors triggered by unreasonable pressure results during AirNet calcs.
With this change, pressures above ANPressErr terminate simulation immediately.
Pressures greater than ANPressWarn trigger warning messages.  A limited number (currently 50 per zone) are displayed.  Any additional warnings are counted (not displayed).  A total warning count is display at the end of the run.  Warnings never cause run termination.
Added documentation for new inputs.
Altered test case ASHPTest2 to produce a few warnings.
No results changes for pre-existing cases except when zone pressures exceed …
> AirNet pressure warnings/errors: add user input / refine logic

- src/CNRECS.DEF
- src/cnglob.h
- src/dhwcalc.cpp
- test/ref/ASHPPKGROOM.REP
Replace the content in this section with:
- Modifies HPWHsim to provide cross-platform conformity.
- Changes the .csv output file pointer hw_pFCSV in dhwcalc from FILE* to std::ofstream*
> HPWHsim cross-platform updates

- doc/checkdoc.bat
- doc/src/records/rsys.md
- src/CNRECS.DEF
1. Changed some RSYS FRACGZ members to FLOATGZ to handle cases such as rsCap17 > rsCap47.
2. Added documentation for rsDefrostModel = NONE
> Minor RSYS fixes

- src/dhwcalc.cpp
Very small DHW loads could cause derived DHWHEATER tank size to be 0.  However, a non-0 tank size is required, so runs encountering this case terminated.
Added code that limits the derived volume to a minimum of 10 gal.
Retested offending case (from user) -- now runs.
No regression test changes.
No documentation changes.
> Bug fix: prevent crash due to autosized DHWHEATER tank volume = 0

- src/dhwcalc.cpp
In DHWSYS configurations with DHWLOOPs with minimal losses, it is possible to have small or no temperature drop across the loop.  When there are no other draws, the water heater inlet temp thus be the same as the outlet.  The code formerly limited the possible delta-T to 1 F and reduced the inlet temp to enforce that.  When the inlet temp was changed in this fashion, an artificial load was created.  Energy balance errors resulted.
Fix: changed the delta-T limit to 0 F.
Note that this does not address the case where the loop return temp is higher than the water heater outlet temp.  That can occur when segment surround temperatures are high and/or when the loop pump has (probably unrealistically) high power.
No regression test results or documentation changes.
> Bug fix: Change DHWLOOP deltaT limit to 0 F (was 1 F)

- src/CNRECS.DEF
- src/cgwthr.cpp
- src/wfpak.cpp
Adds conditional code that writes a CSV file containing design-day data.  This is for model development and comparison.
It is useful to keep this code for possible future use.  Deemed unnecessarily cumbersome to maintain a branch to retain a few lines of code, so they are being added to main as inactive conditional code.
No documentation changes.  No regression test impacts.
> Design day CSV export code

- src/cnguts.cpp
Rework check for duplicate submeter reference.  Prior code worked only for a small number of submeters.
No results changes.  No documentation changes.
> Submeter dupcheck fix

- src/CNDTYPES.DEF
- src/ancrec.cpp
- src/ancrec.h
- src/cncp.cpp
- src/cncult4.cpp
- src/cnhp.cpp
- src/cul.cpp
Change TI from 16 bit (int16_t) to 32 bit (int32_t).  This allows CSE to have more than 32767 records in a given RAT.
No results changes.  No documentation changes.
Note: modified code does not detect / handle other memory limits.  See issue 502.
> 32 bit TI (eliminate 32767 record limit)

- src/cnglob.h
- src/strpak.h
Eliminate redefinition of ctype functions (e.g. isspace) to cause a compiler error.  This scheme allowed detection of possibly incorrect use of such functions.  However, downstream 3rd party #include files that use ctype functions could not be compiled.  In particular, the Mac build failed due to this approach.
Also changed #include <ctype.h> to #include <cctype> as in incremental step toward use of C++ headers as opposed to legacy C headers.
No results changes.  No documentation changes.
> Eliminate strpak.h charTypeErr scheme

- src/CNRECS.DEF
- src/dhwcalc.cpp
- test/DHW02.cse
- test/ref-win32-msvc/dhw02.rep
Eliminate spurious "ignore" messages generated for child DHWSYSs.
> Eliminate spurious 'ignore' message for non-central DHWSYS

- src/CNRECS.DEF
- src/dhwcalc.cpp
DHW energy balance warnings have been seen in CZ16 compliance runs using HPWH.  Isolated the cause to be DWHR (which is typically used only in CZ16).
Fix: Apply mixdown factor (hw_fMixUse) to DWHR recovered energy (qDWHR).  Motivation: qDWHR is derived assuming full draw flow volume.  However, when the mixdown factor is invoked to maintain tUse, the draw is reduced.  Thus, qDWHR should be reduced by the same factor.
Note that "really", the reduced draw would change (increase) the heat exchanger outlet temperature, so qDWHR would be reduced by less than hw_fMixUse.  Currently the heat recovery calculation is done before mixdown is known.  Further, heat recovery is calculated for all ticks in an hour, rather than tick-by-tick.  Substantial code reorganization would be required to capture …
> Bug fix: DWHR accounting correction to fix DHW energy balance warnings

- src/cgcomp.cpp
- src/dhwcalc.cpp
Change handling of airnet convergence failures to tolerate a few convergence failures.  Convergence failures have been seen occasionally in models with a large number of zones (e.g. multifamily cases with e.g. 80 zones).
Was: Max 20 iterations, 1st failure = error (run terminated)
Now: Max 30 iterations, 10 failures treated as warnings (run continues).  11th failure is error.
No results changes (except for runs that formerly did not complete)
No documentation changes.
> First 10 airnet converge failures treated as warnings

- cmake/configure.cmake
SDK version 10.0.20348.0 has been removed as of Visual Studio 17.14.11.
Per release notes --
The following Windows SDK versions have been removed from the Visual Studio 2022 installer: 10.0.18362.0, 10.0.20348.0 and 10.0.22000.0. If your project targets any of these SDKs you may encounter a build error such as: The Windows SDK version 10.0.22000.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". To resolve this, we recommend retargeting your project to 10.0.26100.0, or an earlier supported version if necessary. For a complete list of supported SDK versions please visit: https://developer.microsoft.com/windows/downloads/sdk-archive/.
This PR updates the SDK …
> Update Windows SDK version to 10.0.26100.0

- doc/src/records/rsys.md
- src/curvemap.cpp
Certain combinations of SEER2 and EER2 input into the RESNET method result in cooling COPs at low temperatures above 20. This is not unrealistic, and shouldn't produce an error.
> Remove upper limit on COP in performance maps.
